sudo: false
language: node_js
node_js:
- 5.6 # Latest
- 4.3 # LTS
- 0.1
cache:
  directories:
  - $HOME/.npm
before_install: npm -g install npm@latest
script: npm test -- --timeout 15000
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/broccoli-file-size
    condition: $(node -v | egrep v5.6 | wc -l) = 1
